[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
titanrt = { path = "..", features = ["connector", "reqwest_conn"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
anyhow = "1.0.99"
serde = { version = "1.0.219", features = ["derive"] }